/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _2_main_1_opaque_NodeStruct ;
struct _IO_FILE ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int getpagesize() ;
struct _2_main_1_opaque_NodeStruct {
   struct _2_main_1_opaque_NodeStruct *prev ;
   struct _2_main_1_opaque_NodeStruct *next ;
   int data ;
};
struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_list_1  =    (struct _2_main_1_opaque_NodeStruct *)0;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern unsigned int strlen(char const   *s ) ;
typedef struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_StructureType;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
unsigned long _1_entropy  =    7964669195059714194UL;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
int return_int(void) ;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
unsigned int _2_main__opaque_array[30]  = 
  {      438,      159,      3,      223, 
        439,      5,      313,      103, 
        5,      458,      544,      7, 
        323,      586,      21,      203, 
        404,      83,      203,      12, 
        1,      123,      635,      26, 
        108,      446,      78,      303, 
        54};
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
unsigned long _1_alwaysZero  =    0;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void abort() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void free(void *ptr ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void exit(int status ) ;
extern void signal(int sig , void *func ) ;
int main(int argc , char **argv , char **_formal_envp ) ;
void call(void) ;
typedef struct _IO_FILE FILE;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double log(double x ) ;
struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_ptr_1  =    (struct _2_main_1_opaque_NodeStruct *)0;
extern double ceil(double x ) ;
void call_arg(int a ) ;
void *_3__functionPtrArray[]  = {      & call,      & call + 139,      & return_int,      & call_arg, 
        & call_arg - 878};
extern int fcntl(int filedes , int cmd  , ...) ;
extern int fclose(void *stream ) ;
extern void perror(char const   *str ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_ptr_2  =    (struct _2_main_1_opaque_NodeStruct *)0;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long clock(void) ;
extern long time(long *tloc ) ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern int rand() ;
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern void *malloc(unsigned int size ) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
struct _2_main_1_opaque_NodeStruct *_2_main_1_opaque_list_2  =    (struct _2_main_1_opaque_NodeStruct *)0;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int atoi(char const   *s ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
void megaInit(void) ;
void call_arg(int a ) 
{ 


  {
  printf((char const   */* __restrict  */)"%d\n", a);
  return;
}
}
int main(int argc , char **argv , char **_formal_envp ) 
{ 
  int res ;
  int tmp ;
  int _BARRIER_0 ;
  struct _2_main_1_opaque_NodeStruct *p7 ;
  int i8 ;
  struct _2_main_1_opaque_NodeStruct *p9 ;
  int _2_main__BEGIN_1 ;
  int _2_main__END_1 ;
  int _2_main__BARRIER_2 ;

  {
  megaInit();
  _global_argc = argc;
  _global_argv = argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  {  /* __blockattribute__(__ATOMIC__)*/ 
  _2_main__BEGIN_1 = 1;
  p7 = (struct _2_main_1_opaque_NodeStruct *)malloc(sizeof(struct _2_main_1_opaque_NodeStruct ));
  p7->next = p7;
  p7->prev = p7;
  _2_main_1_opaque_list_1 = p7;
  i8 = 0;
  while (i8 < 4) {
    p9 = (struct _2_main_1_opaque_NodeStruct *)malloc(sizeof(struct _2_main_1_opaque_NodeStruct ));
    p9->data = i8 * ((_1_entropy & ~ 10) - (~ _1_entropy & 10));
    p9->next = _2_main_1_opaque_list_1->next;
    p9->prev = _2_main_1_opaque_list_1;
    (_2_main_1_opaque_list_1->next)->prev = p9;
    _2_main_1_opaque_list_1->next = p9;
    i8 ++;
  }
  _2_main_1_opaque_ptr_1 = _2_main_1_opaque_list_1->next;
  _2_main_1_opaque_ptr_2 = _2_main_1_opaque_ptr_1;
  _2_main_1_opaque_ptr_2 = _2_main_1_opaque_ptr_2->next;
  _2_main__END_1 = 1;
  }
  _2_main__BARRIER_2 = 1;
  ((void (*)(void))_3__functionPtrArray[(int )(_2_main__opaque_array[((unsigned int )(((_1_entropy | 7) + ((long )(_1_entropy | 7) >> 63L)) ^ ((long )(_1_entropy | 7) >> 63L)) % 10) * 3 + 0] % _2_main__opaque_array[5] + -3)])();
  tmp = ((int (*)(void))_3__functionPtrArray[(int )(_2_main__opaque_array[((unsigned int )(((_1_entropy | 10) + ((long )(_1_entropy | 10) >> 63L)) ^ ((long )(_1_entropy | 10) >> 63L)) % 10) * 3 + 0] % _2_main__opaque_array[5] + -1)])();
  _3__functionPtrArray[(((_1_alwaysZero & (((_1_entropy ^ ~ 9) + ((_1_entropy | 9) << 1UL)) + 1UL)) * (_1_alwaysZero | (((_1_entropy ^ ~ 9) + ((_1_entropy | 9) << 1UL)) + 1UL)) + (_1_alwaysZero & ~ (((_1_entropy ^ ~ 9) + ((_1_entropy | 9) << 1UL)) + 1UL)) * (~ _1_alwaysZero & (((_1_entropy ^ ~ 9) + ((_1_entropy | 9) << 1UL)) + 1UL))) | 1) + (((_1_alwaysZero & (((_1_entropy ^ ~ 9) + ((_1_entropy | 9) << 1UL)) + 1UL)) * (_1_alwaysZero | (((_1_entropy ^ ~ 9) + ((_1_entropy | 9) << 1UL)) + 1UL)) + (_1_alwaysZero & ~ (((_1_entropy ^ ~ 9) + ((_1_entropy | 9) << 1UL)) + 1UL)) * (~ _1_alwaysZero & (((_1_entropy ^ ~ 9) + ((_1_entropy | 9) << 1UL)) + 1UL))) & 1)] = & p9;
  res = tmp;
  ((void (*)(int a ))_3__functionPtrArray[(((_1_alwaysZero & ((_1_entropy | 1) - (_1_entropy & 1))) * (_1_alwaysZero | ((_1_entropy | 1) - (_1_entropy & 1))) + (_1_alwaysZero & ~ ((_1_entropy | 1) - (_1_entropy & 1))) * (~ _1_alwaysZero & ((_1_entropy | 1) - (_1_entropy & 1)))) - ~ 3) - 1UL])(res);
  return (0);
}
}
int return_int(void) 
{ 


  {
  return (1);
}
}
void call(void) 
{ 


  {
  printf((char const   */* __restrict  */)"call\n");
  return;
}
}
void megaInit(void) 
{ 


  {

}
}
