/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _1_main_1_opaque_NodeStruct ;
struct _IO_FILE ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
void encodeStrings_litStr2_i$nit(void) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int getpagesize() ;
void encodeStrings_litStr1_i$nit(void) ;
extern int pthread_join(void *thread , void **value_ptr ) ;
char encodeStrings_litStr1[4] ;
extern unsigned int strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
struct _1_main_1_opaque_NodeStruct {
   struct _1_main_1_opaque_NodeStruct *prev ;
   int data ;
   struct _1_main_1_opaque_NodeStruct *next ;
};
struct _1_main_1_opaque_NodeStruct *_1_main_1_opaque_list_2  =    (struct _1_main_1_opaque_NodeStruct *)0;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
char encodeStrings_litStr2[4] ;
extern int pthread_cond_signal(int *cond ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int pthread_mutex_lock(int *mutex ) ;
struct _1_main_1_opaque_NodeStruct *_1_main_1_opaque_list_1  =    (struct _1_main_1_opaque_NodeStruct *)0;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void abort() ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
extern void signal(int sig , void *func ) ;
extern void exit(int status ) ;
void _2_stringEncoder(int n , char str[] ) ;
typedef struct _IO_FILE FILE;
extern int close(int filedes ) ;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double ceil(double x ) ;
void encodeStrings_litStr0_i$nit(void) ;
struct _1_main_1_opaque_NodeStruct *_1_main_1_opaque_ptr_2  =    (struct _1_main_1_opaque_NodeStruct *)0;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int fclose(void *stream ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
char encodeStrings_litStr0[4] ;
struct _1_main_1_opaque_NodeStruct *_1_main_1_opaque_ptr_1  =    (struct _1_main_1_opaque_NodeStruct *)0;
extern int rand() ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern int strcmp(char const   *a , char const   *b ) ;
extern double sqrt(double x ) ;
extern void *malloc(unsigned int size ) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
typedef struct _1_main_1_opaque_NodeStruct *_1_main_1_opaque_StructureType;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int atoi(char const   *s ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
void megaInit(void) ;
void megaInit(void) 
{ 


  {
  encodeStrings_litStr1_i$nit();
  encodeStrings_litStr2_i$nit();
  encodeStrings_litStr0_i$nit();
}
}
void encodeStrings_litStr0_i$nit(void) 
{ 


  {

}
}
void _2_stringEncoder(int n , char str[] ) 
{ 
  int encodeStrings_i3 ;

  {
  encodeStrings_i3 = 0;
  switch (n) {
  case 1: 
  str[encodeStrings_i3] = '%';
  encodeStrings_i3 ++;
  str[encodeStrings_i3] = 'd';
  encodeStrings_i3 ++;
  str[encodeStrings_i3] = '\n';
  encodeStrings_i3 ++;
  str[encodeStrings_i3] = '\000';
  encodeStrings_i3 ++;
  break;
  case 0: 
  str[encodeStrings_i3] = 'h';
  encodeStrings_i3 ++;
  str[encodeStrings_i3] = 'e';
  encodeStrings_i3 ++;
  str[encodeStrings_i3] = 'y';
  encodeStrings_i3 ++;
  str[encodeStrings_i3] = '\000';
  encodeStrings_i3 ++;
  break;
  case 2: 
  str[encodeStrings_i3] = '%';
  encodeStrings_i3 ++;
  str[encodeStrings_i3] = 's';
  encodeStrings_i3 ++;
  str[encodeStrings_i3] = '\n';
  encodeStrings_i3 ++;
  str[encodeStrings_i3] = '\000';
  encodeStrings_i3 ++;
  break;
  }
}
}
void encodeStrings_litStr2_i$nit(void) 
{ 


  {

}
}
void encodeStrings_litStr1_i$nit(void) 
{ 


  {

}
}
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) 
{ 
  int a ;
  char *b ;
  int _BARRIER_0 ;
  struct _1_main_1_opaque_NodeStruct *p7 ;
  int r8 ;
  struct _1_main_1_opaque_NodeStruct *p9 ;
  int r10 ;
  struct _1_main_1_opaque_NodeStruct *p11 ;
  int _1_main__BEGIN_1 ;
  int _1_main__END_1 ;
  int _1_main__BARRIER_2 ;

  {
  megaInit();
  _global_argc = _formal_argc;
  _global_argv = _formal_argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = (_1_main_1_opaque_ptr_1 != _1_main_1_opaque_ptr_2) + (_1_main_1_opaque_ptr_1 == _1_main_1_opaque_ptr_2);
  {  /* __blockattribute__(__ATOMIC__)*/ 
  _1_main__BEGIN_1 = 1;
  p7 = (struct _1_main_1_opaque_NodeStruct *)malloc(24U);
  p7->next = p7;
  p7->prev = p7;
  _1_main_1_opaque_list_1 = p7;
  r10 = rand();
  p11 = (struct _1_main_1_opaque_NodeStruct *)malloc(24U);
  p11->data = 0;
  p11->next = _1_main_1_opaque_list_1->next;
  p11->prev = _1_main_1_opaque_list_1;
  (_1_main_1_opaque_list_1->next)->prev = p11;
  _1_main_1_opaque_list_1->next = p11;
  r8 = rand();
  p9 = (struct _1_main_1_opaque_NodeStruct *)malloc(24U);
  p9->data = r8;
  p9->next = _1_main_1_opaque_list_1->next;
  p9->prev = _1_main_1_opaque_list_1;
  (_1_main_1_opaque_list_1->next)->prev = p9;
  _1_main_1_opaque_list_1->next = p9;
  _1_main_1_opaque_ptr_1 = _1_main_1_opaque_list_1->next;
  _1_main_1_opaque_ptr_2 = _1_main_1_opaque_ptr_1;
  _1_main__END_1 = 1;
  }
  _1_main__BARRIER_2 = (_1_main_1_opaque_ptr_1 != _1_main_1_opaque_ptr_2) + (_1_main_1_opaque_ptr_1 == _1_main_1_opaque_ptr_2);
  a = 42 + ((_1_main_1_opaque_ptr_1 == _1_main_1_opaque_ptr_2) - (_1_main_1_opaque_ptr_1 == _1_main_1_opaque_ptr_2));
  _2_stringEncoder(0, encodeStrings_litStr0);
  b = (char *)(encodeStrings_litStr0);
  _2_stringEncoder(1, encodeStrings_litStr1);
  printf((char const   */* __restrict  */)(encodeStrings_litStr1), a);
  _2_stringEncoder(2, encodeStrings_litStr2);
  printf((char const   */* __restrict  */)(encodeStrings_litStr2), b);
  return (_1_main_1_opaque_ptr_1 != _1_main_1_opaque_ptr_2);
}
}
