/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _IO_FILE ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
void _1_main_main_split_3(char ***argv , int *tmp___0 ) ;
char **_global_argv  =    (char **)0;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
void _1_main_main_split_4(char ***argv , int *a , char **b , unsigned long *c , int *tmp___0 ) ;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern unsigned int strlen(char const   *s ) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
void _1_main_main_split_5(int *a , char **b , unsigned long *c , int *tmp , int *tmp___0 ) ;
extern int pthread_cond_signal(int *cond ) ;
extern int scanf(char const   *format  , ...) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void abort() ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
int main(int argc , char **argv , char **_formal_envp ) ;
extern void signal(int sig , void *func ) ;
extern void exit(int status ) ;
typedef struct _IO_FILE FILE;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double log(double x ) ;
extern double ceil(double x ) ;
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
void _1_main_main_split_1(int *a , char **b , unsigned long *c , int *tmp , int *tmp___0 ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long clock(void) ;
extern long time(long *tloc ) ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern int rand() ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2), __leaf__)) strcmp)(char const   *__s1 ,
                                                                                               char const   *__s2 )  __attribute__((__pure__)) ;
extern double sqrt(double x ) ;
extern void *malloc(unsigned int size ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
void _1_main_main_split_2(int *a , char **b , unsigned long *c ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int atoi(char const   *s ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
void megaInit(void) ;
void _1_main_main_split_2(int *a , char **b , unsigned long *c ) 
{ 


  {
  *a = 1;
  *b = (char *)"yes";
  *c = 18446744073709551615;
}
}
void _1_main_main_split_4(char ***argv , int *a , char **b , unsigned long *c , int *tmp___0 ) 
{ 


  {
  _1_main_main_split_2(& *a, & *b, & *c);
  _1_main_main_split_3(& *argv, & *tmp___0);
}
}
void megaInit(void) 
{ 


  {

}
}
void _1_main_main_split_1(int *a , char **b , unsigned long *c , int *tmp , int *tmp___0 ) 
{ 


  {
  if (*tmp___0 == 0) {
    if (*a == 1) {
      *tmp = strcmp((char const   *)*b, "yes");
      if (*tmp == 0) {
        printf((char const   */* __restrict  */)"b true\n");
      } else
      if (*c == 18446744073709551615) {
        printf((char const   */* __restrict  */)"c true\n");
      } else {
        printf((char const   */* __restrict  */)"a true\n");
      }
    }
  }
}
}
void _1_main_main_split_5(int *a , char **b , unsigned long *c , int *tmp , int *tmp___0 ) 
{ 


  {
  _1_main_main_split_1(& *a, & *b, & *c, & *tmp, & *tmp___0);
}
}
int main(int argc , char **argv , char **_formal_envp ) 
{ 
  int a ;
  char *b ;
  unsigned long c ;
  int tmp ;
  int tmp___0 ;
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = argc;
  _global_argv = argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  _1_main_main_split_4(& argv, & a, & b, & c, & tmp___0);
  _1_main_main_split_5(& a, & b, & c, & tmp, & tmp___0);
  return (0);
}
}
void _1_main_main_split_3(char ***argv , int *tmp___0 ) 
{ 


  {
  *tmp___0 = strcmp((char const   *)*(*argv + 1), "1");
}
}
