/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _IO_FILE ;
struct timeval ;
struct timezone ;
typedef struct timezone * __restrict  __timezone_ptr_t;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) gettimeofday)(struct timeval * __restrict  __tv ,
                                                                                                   __timezone_ptr_t __tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
typedef long __suseconds_t;
extern int pthread_join(void *thread , void **value_ptr ) ;
struct timezone {
   int tz_minuteswest ;
   int tz_dsttime ;
};
extern int open(char const   *filename , int oflag  , ...) ;
extern unsigned int strlen(char const   *s ) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
void *_1_tigress_init__externalFunctionPtrArray[2] ;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
typedef int __pid_t;
extern  __attribute__((__nothrow__)) __pid_t ( __attribute__((__leaf__)) getpid)(void) ;
extern int scanf(char const   *format  , ...) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int pthread_mutex_lock(int *mutex ) ;
void _1_tigress_init__externalFunctionPtrArray_i$nit(void) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern void abort() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void free(void *ptr ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void signal(int sig , void *func ) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
extern void exit(int status ) ;
typedef struct _IO_FILE FILE;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double log(double x ) ;
extern double ceil(double x ) ;
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
typedef long __time_t;
struct timeval {
   __time_t tv_sec ;
   __suseconds_t tv_usec ;
};
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long clock(void) ;
extern long time(long *tloc ) ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern int rand() ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern int strcmp(char const   *a , char const   *b ) ;
extern double sqrt(double x ) ;
void tigress_init(void) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern void *malloc(unsigned int size ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int atoi(char const   *s ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
void megaInit(void) ;
void _1_tigress_init__externalFunctionPtrArray_i$nit(void) 
{ 


  {

}
}
void megaInit(void) 
{ 


  {
  _1_tigress_init__externalFunctionPtrArray_i$nit();
}
}
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) 
{ 
  int x ;
  __pid_t tmp ;
  struct timeval tv ;
  int y ;
  int tmp___0 ;
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = _formal_argc;
  _global_argv = _formal_argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  tigress_init();
  tmp = ((__pid_t ( __attribute__((__leaf__)) (*))(void))_1_tigress_init__externalFunctionPtrArray[1])();
  x = tmp;
  printf((char const   */* __restrict  */)"pid: %i\n", x);
  tmp___0 = ((int ( __attribute__((__nonnull__(1), __leaf__)) (*))(struct timeval * __restrict  __tv ,
                                                                   __timezone_ptr_t __tz ))_1_tigress_init__externalFunctionPtrArray[0])((struct timeval */* __restrict  */)(& tv),
                                                                                                                                         (__timezone_ptr_t )((void *)0));
  y = tmp___0;
  printf((char const   */* __restrict  */)"time of day: %ld.%06ld\n", tv.tv_sec, tv.tv_usec);
  return (0);
}
}
void tigress_init(void) 
{ 
  void *externalAddr1 ;

  {
  externalAddr1 = dlsym((void *)0, "gettimeofday");
  _1_tigress_init__externalFunctionPtrArray[0] = externalAddr1;
  externalAddr1 = dlsym((void *)0, "getpid");
  _1_tigress_init__externalFunctionPtrArray[1] = externalAddr1;
  return;
}
}
